---
# file: /roles/hdfs/tasks/main.yml

- name: Create hdfs target dir on remote node
  file: path={{ hadoop_install_dir }} state=directory recurse=yes
  
- name: Push Hadoop tar ball to target node and untar
  unarchive: src={{ hadoop_tar_src }} dest={{ hadoop_install_dir }} copy=yes
  
- name: Create hdfs target dir on remote node
  file: path={{ java_install_dir }} state=directory recurse=yes
