---
# file: /roles/hdfs/tasks/main.yml

- name: Create hdfs target dir on remote node
  file: path={{ hadoop_install_dir }} state=directory recurse=yes owner={{ hadoop_user }}:{{ hadoop_user }} mode=0755
  
- name: Create dir 'dfs.name.dir' on remote node
  file: path={{ dfs_name_dir }} state=directory recurse=yes
  
- name: Create dir 'dfs.data.dir' on remote node
  file: path={{ dfs_data_dir }} state=directory recurse=yes
  
- name: Create dir 'dfs.namenode.checkpoint.dir' on remote node
  file: path={{ dfs_namenode_checkpoint_dir }} state=directory recurse=yes  
  
- name: Push Hadoop tar ball to target node and untar
  unarchive: src={{ hadoop_tar_src }} dest={{ hadoop_install_dir }} copy=yes
  
- name: Create hdfs target dir on remote node
  file: path={{ java_install_dir }} state=directory recurse=yes
