---
# This Playbook is supposed to connfigure a fully configured HDFS cluster.

- hosts: all
  roles:
   - role: ntp

# - hosts: namenodes
#   roles:
#   - role: namenode

# - hosts: secondary_namenodes
#   roles:
#   - role: secondary_namenode

# - hosts: datanodes
#   roles:
#   - role: datnode
