---
# This Playbook is supposed to configure a fully configured HDFS cluster.

- hosts: tag_basic_true
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  roles:
  - role: ssh
  - role: aws
#   - role: ntp

- hosts: tag_java_true
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  roles:
  - role: java

- hosts: tag_hdfs_true
  remote_user: ubuntu
  gather_facts: yes
  roles:
  - role: hdfs

# - hosts: secondary_namenodes
#   roles:
#   - role: secondary_namenode

# - hosts: datanodes
#   roles:
#   - role: datnode
