---
# This Playbook is supposed to connfigure a fully configured HDFS cluster.

- hosts: cluster
  remote_user: ubuntu
  sudo: true
  gather_facts: no
  roles:
#   - role: ntp
    - role: java
    - role: hdfs

#- hosts: hdfs_nodes
#  remote_user: ubuntu
#  gather_facts: no
#  roles:
#  - role: hdfs

# - hosts: secondary_namenodes
#   roles:
#   - role: secondary_namenode

# - hosts: datanodes
#   roles:
#   - role: datnode
