---
# This Playbook is supposed to connfigure a fully configured HDFS cluster.

- hosts: cluster
  remote_user: ubuntu
  gather_facts: no
  roles:
#   - role: ntp
    - role: java

# - hosts: namenodes
#   roles:
#   - role: namenode

# - hosts: secondary_namenodes
#   roles:
#   - role: secondary_namenode

# - hosts: datanodes
#   roles:
#   - role: datnode
