---
# This Playbook is supposed to configure a fully configured HDFS cluster.

- hosts: all
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  roles:
  - role: ssh
#   - role: ntp

- hosts: cluster
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  roles:
  - role: java

- hosts: cluster
  remote_user: ubuntu
  gather_facts: yes
  roles:
  - role: hdfs

# - hosts: secondary_namenodes
#   roles:
#   - role: secondary_namenode

# - hosts: datanodes
#   roles:
#   - role: datnode
