# file: /roles/java/vars/main.yml

# Source folder on Ansible coordinator that contains a Oracle Java 7 tar ball
java_tar_src : /home/ubuntu/jdk-7u67-linux-x64.tar

# Target folder on remote nodes to install Oracle JAva 7
java_home : /opt/java/64/oracle-java7
