# file: /roles/ssh/tasks/main.yml

- name: Remove ssh key file on remote node
  file: path={{ ssh_private_key_target }} state=absent
  sudo: yes

- name: Push ssh key file to remote node
  copy: src={{ ssh_private_key_target }} dest="{{ ssh_home }}/" owner={{ ssh_user }} group={{ ssh_user }} mode="u+rw,g-rwx,o-rwx"
  
#- name: Set permissions on SSH folder
#  file: path="{{ ssh_home }}/" owner={{ ssh_user }} group={{ ssh_user }} mode=0700
  
#- name: Set permissions on SSH private key file
#  file: path={{ ssh_private_key_target }} state=file owner={{ ssh_user }} group={{ ssh_user }} mode=0600
