# file: /roles/ssh/tasks/main.yml

- name: Create conf file '/etc/hosts'
  sudo : yes
  template: > 
    src=hosts.j2 
    dest=/etc/hosts mode=0644

- name: Remove ssh key file on remote node
  sudo: yes
  file: > 
    path={{ ssh_private_key_target }}
    state=absent

- name: Push ssh key file to remote node
  sudo: yes
  copy: >
    src={{ ssh_private_key_source }}
    dest="{{ ssh_home }}/"
    owner={{ ssh_user }}
    group={{ ssh_user }}
    mode="0600"
  
- name: Set permissions on SSH private key file to 600
  sudo: yes
  shell: chmod 600 /home/ubuntu/.ssh/id_rsa
  register: chmod_cmd
  
- debug: var=chmod_cmd.stdout_lines
  
#- name: Set permissions on SSH folder
#  file: path="{{ ssh_home }}/" owner={{ ssh_user }} group={{ ssh_user }} mode=0700
  
#- name: Set permissions on SSH private key file
#  file: path={{ ssh_private_key_target }} state=file owner={{ ssh_user }} group={{ ssh_user }} mode=0600
