# file: /roles/ssh/tasks/main.yml

- name: Remove ssh key file on remote node
  file: path={{ ssh_private_key_target }} state=absent
  sudo: yes

- name: Push ssh key file to remote node
  copy: src={{ ssh_private_key_target }} dest="{{ ssh_home }}/" owner={{ ssh_user }} group={{ ssh_user }} mode="0600"
  
- name: Set permissions on SSH private key file to 600
  shell: chmod 600 /home/ubuntu/.ssh/id_rsa
  register: chmod_cmd
  
- debug: var=chmod_cmd.stdout_lines
  
#- name: Set permissions on SSH folder
#  file: path="{{ ssh_home }}/" owner={{ ssh_user }} group={{ ssh_user }} mode=0700
  
#- name: Set permissions on SSH private key file
#  file: path={{ ssh_private_key_target }} state=file owner={{ ssh_user }} group={{ ssh_user }} mode=0600
