# file: /roles/hdfs/vars/main.yml

namenode_dns: ip-{{ node1 }}.eu-west-1.compute.internal
secondary_namenode_dns: ip-{{ node2 }}.eu-west-1.compute.internal
hadoop_ganglia_metad_ip: {{ node1 }}

dfs_replication: 1
dfs_name_dir: /home/ubuntu/data/nn
dfs_data_dir: /home/ubuntu/data/dn
dfs_namenode_checkpoint_dir: /home/ubuntu/data/sn

hadoop_heapsize: 2000
hadoop_java_home: {{ java_home }}
