# file: /roles/hdfs/vars/main.yml

hadoop_version: 1.2.1
hadoop_user: ubuntu
hadoop_tar_src: "/home/ubuntu/hadoop-{{ hadoop_version }}.tar.gz"

namenode_dns: "ip-{{ node1_private_ip }}.eu-west-1.compute.internal"
secondary_namenode_dns: "ip-{{ node2_private_ip }}.eu-west-1.compute.internal"
hadoop_ganglia_metad_ip: "{{ node1_private_ip }}"

dfs_replication: 1

hadoop_install_dir: /home/ubuntu
hadoop_home_dir: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}"
dfs_name_dir: /home/ubuntu/data/nn
dfs_data_dir: /home/ubuntu/data/dn
dfs_namenode_checkpoint_dir: /home/ubuntu/data/sn

hadoop_heapsize: 2000
hadoop_java_home: /opt/java/64/oracle-java7/jdk1.7.0_67/
