# file: /roles/hdfs/vars/main.yml
# Expected Inventory Groups
#   - tag_namenode_true         [2DO: Change to tag_hdfsNamenode_true]
#   - tag_secondarynamenode_true     [2DO: Change to tag_hdfsSecondarynamenode_true]
#   - tag_gmetad_true      [2DO: Change to tag_gangliaMetad_true]

hadoop_version: 1.2.1
hadoop_user: ubuntu
hadoop_tar_src: "/home/jk/ansible/software/hadoop-{{ hadoop_version }}.tar.gz"

namenode_ip: "{{ hostvars[groups['tag_namenode_true'][0]]['ansible_eth0']['ipv4']['address'] }}"
namenode_dns: "ip-{{ hostvars[groups['tag_namenode_true'][0]]['ansible_eth0']['ipv4']['address'] }}.eu-west-1.compute.internal"
secondary_namenode_dns: "ip-{{ hostvars[groups['tag_secondarynamenode_true'][0]]['ansible_eth0']['ipv4']['address'] }}.eu-west-1.compute.internal"
hadoop_ganglia_metad_ip: "{{ hostvars[groups['tag_gmetad_true'][0]]['ansible_eth0']['ipv4']['address'] }}"

dfs_replication: 1

hadoop_install_dir: /home/ubuntu

hadoop_home_dir: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}"
hadoop_data_dir: "{{ hadoop_install_dir }}/data"

dfs_name_dir: "{{ hadoop_data_dir }}/nn"
dfs_data_dir: "{{ hadoop_data_dir }}/dn"
dfs_namenode_checkpoint_dir: "{{ hadoop_data_dir }}/sn"
dfs_tmp_dir: "{{ hadoop_data_dir }}/tmp"

hadoop_heapsize: 2000
# [2DO: Import Java home dir from java role]
hadoop_java_home: /opt/java/64/oracle-java7/jdk1.7.0_67/
