---
# file: /roles/hbase/vars/main.yml

hbase_version: 0.94.18
hbase_user: ubuntu
hbase_tar_src: "/home/jk/ansible/software/hbase-{{ hbase_version }}.tar.gz"

hmaster_ip: "{{ hostvars[groups['tag_master_true'][0]]['ansible_eth0']['ipv4']['address'] }}"
namenode_dns: "ip-{{ hostvars[groups['tag_namenode_true'][0]]['ansible_eth0']['ipv4']['address'] }}.eu-west-1.compute.internal"
zookeeper_ip: "{{ hostvars[groups['tag_zookeeper_true'][0]]['ansible_eth0']['ipv4']['address'] }}"
gmetad_ip: "{{ hostvars[groups['tag_gmetad_true'][0]]['ansible_eth0']['ipv4']['address'] }}"

dfs_replication: 1

hbase_install_dir: /home/ubuntu

hbase_home_dir: "{{ hbase_install_dir }}/hbase-{{ hbase_version }}"
hbase_data_dir: "{{ hbase_install_dir }}/data"

db_regionserver_dir: "{{ hbase_data_dir }}/rn"

hbase_heapsize: 2000
# [2DO: Import Java home dir from java role]
hbase_java_home: /opt/java/64/oracle-java7/jdk1.7.0_67/
